[package]
name = "bcm283x-v3d"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Low-level driver for the Broadcom VideoCore IV V3D 3D engine (Raspberry Pi 0-3, Zero 2W)"
keywords = ["raspberry-pi", "v3d", "gpu", "3d", "bcm283x"]
categories = ["embedded", "no-std", "hardware-support"]
license.workspace = true
repository.workspace = true

[dependencies]
kspin = "0.1"
log.workspace = true
rdif-base.workspace = true
